name: TreasureHunt
main: com.danangell.treasurehunt.TreasureHunt
version: 1.0.0
api-version: 1.20
commands:
  treasurehunt:
    description: Start and manage a treasure hunt
    usage: /treasurehunt <start|stop|status>
    executor: com.danangell.treasurehunt.TreasureHuntCommand
    tab-completer: com.danangell.treasurehunt.TreasureHuntCommand
